trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Hello, world!"
  displayName: Run a one-line script

- task: Docker@2
  displayName: Build Docker image
  inputs:
    command: build
    dockerfile: docker/Dockerfile
    buildContext: .
    repository: myapp
    tags: |
      latest
